# Generated by Django 5.0.7 on 2024-07-28 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "channels",
            "0002_channel_content_type_channel_name_channel_object_id_and_more",
        ),
        ("email_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        help_text="Separe cada destinatário com vírgula (,)",
                        verbose_name="Destinatários",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Assunto")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Mensagem"),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="channels.channel",
                        verbose_name="Canal",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="email_app.template",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
