services:
  - type: web
    name: vibbra-notify-system
    plan: free
    runtime: python
    env: python
    buildCommand: ./build.sh
    startCommand: poetry run gunicorn --pythonpath src setup.wsgi
