# Generated by Django 5.0.7 on 2024-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("email_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("web_push", "email", "sms")},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="name",
            field=models.CharField(default="Temp", max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="email_app.template",
            ),
        ),
    ]
