# Generated by Django 5.0.7 on 2024-07-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "channels",
            "0002_channel_content_type_channel_name_channel_object_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[("web_push", "Web Push"), ("email", "E-mail"), ("sms", "SMS")],
                max_length=50,
                verbose_name="Tipo de Canal",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=55, verbose_name="Nome"),
        ),
    ]
